# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies (extension)"
  - package-ecosystem: "npm"
    directory: "/native-host" # Location of package manifests
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies (native app)"
 - package-ecosystem: "pip"
    directory: "/native-host" # Location of package manifests
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "pip dependencies (native app)"
